#ifndef __EC11_HANDLE_H
#define __EC11_HANDLE_H
#include <stdint.h>
#include <stdbool.h>

#include "EncoderEC11.h"

#define EC11_TASK_TIME 1
#define KEY_LONG_PRESS_TIME 10


typedef enum
{
	AIR_TEMP_ADD,
	AIR_TEMP_REDUCE,
	AIR_TEMP_ADD_FIVE,
	AIR_TEMP_REDUCE_FIVE,
	AIR_TEMP_EC11_END_EVENT,
	EXIT_SET,
	RESET_DS01_VALUE,
} air_temp_ec11_event_e;

typedef enum
{
	SOL_TEMP_ADD,
	SOL_TEMP_REDUCE,
	SOL_TEMP_ADD_FIVE,
	SOL_TEMP_REDUCE_FIVE,
	AIR_TEMP_CAL_ADD,
	AIR_TEMP_CAL_ADD_FIVE,
	AIR_TEMP_CAL_REDUCE,
	AIR_TEMP_CAL_REDUCE_FIVE,
	SOL_TEMP_CAL_ADD,
	SOL_TEMP_CAL_ADD_FIVE,
	SOL_TEMP_CAL_REDUCE,
	SOL_TEMP_CAL_REDUCE_FIVE,
	SET_UNIT,
	SET_SPEAK,
	SET_DISPLAY_LOCK,
	SET_SLEEP_STATE,
	SOL_SLEEP_TIME_ADD,
	SOL_SLEEP_TIME_REDUCE,
	SOL_SLEEP_TIME_ADD_FIVE,
	SOL_SLEEP_TIME_REDUCE_FIVE,
	SOL_TEMP_EC11_END_EVENT,
} sol_temp_ec11_event_e;

typedef enum
{
	AIR_ADD,
	AIR_REDUCE,
	AIR_ADD_FIVE,
	AIR_REDUCE_FIVE,
	
	AIR_EC11_END_EVENT,
} air_ec11_event_e;

void ec11_handle(void);

#endif // __ENCODER_EC11_H
