#ifndef __OUTPUT_H
#define __OUTPUT_H
#include "flash.h"
#define FLASH_TASK_TIME            50
#define DATA_SIZE                  2
#define FLASH_MENBER               20



/* a area data address */
/* handle data */
#define A_SET_AIR_TEMP_ADDRESS           (0x08000000 + 1024 * 125)
#define A_SET_AIR_ADDRESS                A_SET_AIR_TEMP_ADDRESS + DATA_SIZE   
#define A_CH1_SET_AIR_TEMP_ADDRESS       A_SET_AIR_ADDRESS + DATA_SIZE   
#define A_CH1_SET_WIND_ADDRESS           A_CH1_SET_AIR_TEMP_ADDRESS + DATA_SIZE   
#define A_CH2_SET_AIR_TEMP_ADDRESS       A_CH1_SET_WIND_ADDRESS + DATA_SIZE   
#define A_CH2_SET_WIND_ADDRESS           A_CH2_SET_AIR_TEMP_ADDRESS + DATA_SIZE   
#define A_CH3_SET_AIR_TEMP_ADDRESS  	 A_CH2_SET_WIND_ADDRESS + DATA_SIZE  
#define A_CH3_SET_WIND_ADDRESS 			 A_CH3_SET_AIR_TEMP_ADDRESS + DATA_SIZE 
#define A_SET_SOL_TEMP_ADDRESS			 A_CH3_SET_WIND_ADDRESS + DATA_SIZE 
#define A_CH1_SET_SOL_TEMP_ADDRESS       A_SET_SOL_TEMP_ADDRESS + DATA_SIZE 
#define A_CH2_SET_SOL_TEMP_ADDRESS       A_CH1_SET_SOL_TEMP_ADDRESS + DATA_SIZE 
#define A_CH3_SET_SOL_TEMP_ADDRESS       A_CH2_SET_SOL_TEMP_ADDRESS + DATA_SIZE 
#define A_TEMP_UNIT_ADDRESS     		 A_CH3_SET_SOL_TEMP_ADDRESS + DATA_SIZE   
#define A_SPEAK_MODE_ADDRESS   			 A_TEMP_UNIT_ADDRESS + DATA_SIZE  
#define A_AIR_CAL_DATA_ADDRESS     	     A_SPEAK_MODE_ADDRESS + DATA_SIZE 
#define A_SOL_CAL_DATA_ADDRESS   		 A_AIR_CAL_DATA_ADDRESS + DATA_SIZE 
#define A_DISPLAY_LOCK_MODE_ADDRESS      A_SOL_CAL_DATA_ADDRESS + DATA_SIZE   
#define A_AIR_SLEEP_MODE_ADDRESS         A_DISPLAY_LOCK_MODE_ADDRESS + DATA_SIZE  
#define A_SOL_SLEEP_TIME_ADDRESS         A_AIR_SLEEP_MODE_ADDRESS + DATA_SIZE  
#define A_FLASH_VERSION_ADDRESS          A_SOL_SLEEP_TIME_ADDRESS + DATA_SIZE                         

/* b area data address */
/* handle data */
#define B_SET_AIR_TEMP_ADDRESS           (0x08000000 + 1024 * 127)
#define B_SET_AIR_ADDRESS                B_SET_AIR_TEMP_ADDRESS + DATA_SIZE   
#define B_CH1_SET_AIR_TEMP_ADDRESS       B_SET_AIR_ADDRESS + DATA_SIZE   
#define B_CH1_SET_WIND_ADDRESS           B_CH1_SET_AIR_TEMP_ADDRESS + DATA_SIZE   
#define B_CH2_SET_AIR_TEMP_ADDRESS       B_CH1_SET_WIND_ADDRESS + DATA_SIZE   
#define B_CH2_SET_WIND_ADDRESS           B_CH2_SET_AIR_TEMP_ADDRESS + DATA_SIZE   
#define B_CH3_SET_AIR_TEMP_ADDRESS  	 B_CH2_SET_WIND_ADDRESS + DATA_SIZE  
#define B_CH3_SET_WIND_ADDRESS 			 B_CH3_SET_AIR_TEMP_ADDRESS + DATA_SIZE 
#define B_SET_SOL_TEMP_ADDRESS			 B_CH3_SET_WIND_ADDRESS + DATA_SIZE 
#define B_CH1_SET_SOL_TEMP_ADDRESS       B_SET_SOL_TEMP_ADDRESS + DATA_SIZE 
#define B_CH2_SET_SOL_TEMP_ADDRESS       B_CH1_SET_SOL_TEMP_ADDRESS + DATA_SIZE 
#define B_CH3_SET_SOL_TEMP_ADDRESS       B_CH2_SET_SOL_TEMP_ADDRESS + DATA_SIZE 
#define B_TEMP_UNIT_ADDRESS     		 B_CH3_SET_SOL_TEMP_ADDRESS + DATA_SIZE   
#define B_SPEAK_MODE_ADDRESS   			 B_TEMP_UNIT_ADDRESS + DATA_SIZE  
#define B_AIR_CAL_DATA_ADDRESS     	     B_SPEAK_MODE_ADDRESS + DATA_SIZE 
#define B_SOL_CAL_DATA_ADDRESS   		 B_AIR_CAL_DATA_ADDRESS + DATA_SIZE 
#define B_DISPLAY_LOCK_MODE_ADDRESS      B_SOL_CAL_DATA_ADDRESS + DATA_SIZE   
#define B_AIR_SLEEP_MODE_ADDRESS         B_DISPLAY_LOCK_MODE_ADDRESS + DATA_SIZE  
#define B_SOL_SLEEP_TIME_ADDRESS         B_AIR_SLEEP_MODE_ADDRESS + DATA_SIZE  
#define B_FLASH_VERSION_ADDRESS          B_SOL_SLEEP_TIME_ADDRESS + DATA_SIZE    

typedef enum
{
    FLASH_START = 0,
    FLASH_HANDLE_DATA,
    FLASH_GENERAL_DATA,
    FLASH_FINSH,
} flash_state_t;


typedef struct
{
    flash_state_t state;
} flash_handle_t;

void FlashProc(void);


#endif
